#!/opt/bin/php
<?php

require __DIR__.'/vendor/autoload.php';
require_once $_ENV['LAMBDA_TASK_ROOT'] . '/src/' . $handlerFunction . '.php';

while (true) {
    $client = new \GuzzleHttp\Client();

    $request = getNextRequest($client);

    $handlerFunction = array_slice(explode('.', $_ENV['_HANDLER']), -1)[0];

    try {
        $response = $handlerFunction($request['payload']);
    } catch (\Exception $e) {
        handleInvocationError($client, $request['invocationId'], $e);
        continue;
    }

    sendResponse($request['invocationId'], $response);
}

function getNextRequest($client): array
{
    $response = $client->get('http://'.$_ENV['AWS_LAMBDA_RUNTIME_API'].'/2018-06-01/runtime/invocation/next');

    return [
        'invocationId' => $response->getHeader('Lambda-Runtime-Aws-Request-Id')[0],
        'payload' => json_decode((string) $response->getBody(), true)
    ];
}

function sendResponse($client, $invocationId, $response)
{
    $client->post(
        'http://' . $_ENV['AWS_LAMBDA_RUNTIME_API'] . '/2018-06-01/runtime/invocation/' . $invocationId . '/response',
        ['body' => $response]
    );
}

function handleInvocationError($client, $invocationId, \Exception $e)
{
    $client->post(
        'http://' . $_ENV['AWS_LAMBDA_RUNTIME_API'] . '/2018-06-01/runtime/invocation/' . $invocationId . '/error',
        ['body' => $response]
    );
}